#!/bin/bash

set -e

cd "$(dirname "$0")"
source ../aws.env

cd /home/vhosts
aws s3 sync . s3://s3-bucket-linode-backup-us-west-1/vhosts-backup/ \
    --no-follow-symlinks \
    --no-progress \
    --exclude __pycache__ \
    --storage-class INTELLIGENT_TIERING
