#!/bin/bash
#########################################################################################
#
# This script runs as a cron job every hour to try to publish
#
# How does it work?
#   1. It looks at the RSS feed to determine the most next episode number
#   2. It checks if a pull request already exists for that episode number in GitHub, and if so, there is nothing else to do
#   3. It looks in S3 for the next episode mp3 file
#   3. It runs the `upload` script on that file.
#
# How does the mp3 file get to S3?
#   A Zapier zap copies the file from Google Drive (the "SSE Edited Episodes" folder) to S3.
#
# How does the mp3 file get into Google Drive?
#   The editors manually put the mp3 into Google Drive after editing. They must follow the
#   naming convention `sse-XXX.mp3` for this automation to find the file.
#
# What's the cron entry?
#
#   0 * * * * /home/dave/soft-skills-engineering/website/scripts/cron-auto-publish
#
##########################################################################################

cd "$(dirname "$0")"

latest_published_epispode_number=$(curl --silent --fail 'http://softskills.audio/feed.xml' \
        | egrep 'sse-[0-9]+\.mp3' \
        | sed -e 's/.*sse-//' \
        | sed -e 's/\.mp3.*//' \
        | sort -n \
        | tail -n 1)

episode_number_to_publish=$((latest_published_epispode_number + 1))

if ./fetch-pull-request $episode_number_to_publish >/dev/null; then
    echo "Nothing to do. Pull request already exists for episode $episode_number_to_publish"
    exit 0
fi

mp3_file_base_name="sse-$episode_number_to_publish.mp3"
tmpdir=$(mktemp -d -t sse-XXXXXXXXXX)
mp3_downloaded_absolute_file_path="$tmpdir/$mp3_file_base_name"
s3_bucket_url="https://s3-bucket-us-west-1-public-podcast-episodes.s3-us-west-1.amazonaws.com/$mp3_file_base_name"

curl_success=0
echo "Attempting to download from S3:"
echo "  S3 URL: $s3_bucket_url"
echo "  Target file: $mp3_downloaded_absolute_file_path"
curl --fail --silent "$s3_bucket_url" > "$mp3_downloaded_absolute_file_path"
if [ $? -eq 0 ]; then
    echo "Successful download!"
    curl_success=1
else
    echo "Error: Episode $episode_number_to_publish is not in S3 yet. Searched for it here: $s3_bucket_url"
fi

if [ $curl_success -eq 0 ]; then
    exit_code=1
elif file "$mp3_downloaded_absolute_file_path" | grep -i -E '(audio file|MPEG.*layer III)' >/dev/null; then
    ./upload --unattended "$mp3_downloaded_absolute_file_path"
    exit_code=$?
else
    exit_code=1
    echo
    echo "Error: downloaded mp3 file is not an audio file"
    echo
    echo "File output we checked:"
    file "$mp3_downloaded_absolute_file_path"
fi

# Clean up
rm -rf "$tmpdir"

if [ $exit_code -eq 0 ]; then
    echo "Finished successfully at: $(date)"
else
    echo "Finshing unsuccessfully at: $(date)"
fi
exit $exit_code
