#!/bin/bash
#########################################################################################
#
# This script runs as a cron job every hour to try to publish
#
# How does it work?
#   1. It looks at the RSS feed to determine the most next episode number
#   2. It checks if a pull request already exists for that episode number in GitHub, and if so, there is nothing else to do
#   3. It looks in S3 for the next episode mp3 file
#   3. It runs the `upload` script on that file.
#
# How does the mp3 file get to S3?
#   A Zapier zap copies the file from Google Drive (the "SSE Edited Episodes" folder) to S3.
#
# How does the mp3 file get into Google Drive?
#   The editors manually put the mp3 into Google Drive after editing. They must follow the
#   naming convention `sse-XXX.mp3` for this automation to find the file.
#
# What's the cron entry?
#
# See `crontab -l`:
#
#   0 * * * * /home/dave/soft-skills-engineering/website/scripts/cron-auto-publish
#
##########################################################################################

# Change to 1 to see debug output
DEBUG=0

[ $DEBUG -eq 1 ] && echo "Starting at $(date)"

cd "$(dirname "$0")"
source venv/bin/activate

# Determine the next episode number to publish:
latest_published_epispode_number=$(curl --silent --fail 'http://softskills.audio/feed.xml' \
        | egrep 'sse-[0-9]+\.mp3' \
        | sed -e 's/.*sse-//' \
        | sed -e 's/\.mp3.*//' \
        | sort -n \
        | tail -n 1
    )

episode_number_to_publish=$((latest_published_epispode_number + 1))

[ $DEBUG -eq 1 ] && echo "Checking for pull request for episode $episode_number_to_publish"
if ./fetch-pull-request $episode_number_to_publish >/dev/null 2>&1; then
    [ $DEBUG -eq 1 ] && echo "Pull request already exists for episode $episode_number_to_publish, so we have nothing to do"
    exit 0
fi

mp3_file_base_name="sse-$episode_number_to_publish.mp3"
mp3_s3_url="https://s3-bucket-us-west-1-public-podcast-episodes.s3-us-west-1.amazonaws.com/$mp3_file_base_name"
tmpdir=$(mktemp -d -t sse-XXXXXXXXXX)
mp3_local_file_name="$tmpdir/$mp3_file_base_name"

if [ $DEBUG -eq 1 ]; then
    echo "Attempting to download from S3:"
    echo "  S3 URL: $mp3_s3_url"
    echo "  Target file: $mp3_local_file_name"
fi

curl --fail --silent "$mp3_s3_url" > "$mp3_local_file_name"
if [ $? -ne 0 ]; then
    [ $DEBUG -eq 1 ] && echo "Error: Episode $episode_number_to_publish is not in S3 yet. Searched for it here: $mp3_s3_url"
    exit_code=1
elif file "$mp3_local_file_name" | grep -i -E '(audio file|MPEG.*layer III)' >/dev/null; then
    [ $DEBUG -eq 1 ] && echo "Successful mp3 download. Confirmed mp3 file type. Publishing episode..."
    ./upload --unattended "$mp3_local_file_name"
    exit_code=$?
else
    exit_code=1
    echo "Error: downloaded mp3 file is not an audio file: $mp3_s3_url"
fi

# Clean up
rm -rf "$tmpdir"

if [ $exit_code -eq 0 ]; then
    [ $DEBUG -eq 1 ] && echo "Finished successfully at: $(date)"
else
    [ $DEBUG -eq 1 ] && echo "Finshing unsuccessfully at: $(date)"
fi

exit $exit_code
