#!/usr/bin/env python3
import re
from trello import set_up, get_question_cards, get_show_notes

def format_questions(questions):
  ret = []
  for question in questions:
    lines = question.split('\n')
    if lines and lines[0].lower().startswith('from') or 'anonymous' in lines[0].lower():
      del lines[0]
    if lines[0].strip() == '':
      del lines[0]
    for i, line in enumerate(lines):
      line = line.strip()
      if i > 0:
        line = '   ' + line
      lines[i] = line
    question = '\n'.join(lines)
    question = re.sub('^"', '', question)
    question = re.sub('"$', '', question)
    ret.append(question)
  return ret

episode_number, key, token = set_up()
question_cards = get_question_cards(key, token, episode_number)
questions = [card['desc'] for card in question_cards]
formatted_questions = format_questions(questions)

notes = get_show_notes(key, token, episode_number)

for count, question in enumerate(formatted_questions):
  print('{}. {}\n'.format(count+1, question))

if notes:
  print('## Show Notes\n{}'.format(notes))

